let DATA=null; let currentMonth=null; const codeLabels={G:'Garde 24h',RG:'Repos garde','18':'8h–18h','18h':'8h–18h',A:'Absence / activité A',CP:'Congé',F:'Formation',E:'Enseignement',R:'Récupération',I:'Indisponible'};
const kpiDefs=[['G','Gardes 24h'],['18','Journées 18h'],['RG','Repos garde'],['A','A / absences'],['F','Formations']];
function norm(v){return String(v||'').trim()} function codeClass(c){let x=norm(c).replace('18h','18'); return x==='18'?'H18':x.replace(/[^a-zA-Z0-9]/g,'')} function isWeekend(w){return w==='S'||w==='D'}
async function init(){DATA=await fetch('./planning.json').then(r=>r.json()); currentMonth=DATA.months[0].id; const now=new Date(); const found=DATA.months.find(m=>m.year===now.getFullYear()&&m.month===now.getMonth()+1); if(found) currentMonth=found.id; buildTabs(); buildLegend(); bind(); render();}
function bind(){document.getElementById('searchInput').addEventListener('input',render);document.getElementById('todayBtn').addEventListener('click',()=>{const now=new Date(); const f=DATA.months.find(m=>m.year===now.getFullYear()&&m.month===now.getMonth()+1); if(f){currentMonth=f.id;render();buildTabs();}})}
function buildTabs(){const el=document.getElementById('monthTabs'); el.innerHTML=''; DATA.months.forEach(m=>{const b=document.createElement('button'); b.textContent=m.label.replace(' 2026',''); b.className=m.id===currentMonth?'active':''; b.onclick=()=>{currentMonth=m.id; buildTabs(); render();}; el.appendChild(b);});}
function buildLegend(){const el=document.getElementById('legend'); el.innerHTML=''; ['G','18','RG','A','CP','F','R','I'].forEach(c=>{const s=document.createElement('span'); s.className='chip '+codeClass(c); s.textContent=c; s.title=codeLabels[c]||c; el.appendChild(s);});}
function render(){const m=DATA.months.find(x=>x.id===currentMonth); const q=norm(document.getElementById('searchInput').value).toLowerCase(); const doctors=m.doctors.filter(d=>d.name.toLowerCase().includes(q)); document.getElementById('monthLabel').textContent=m.label; document.getElementById('doctorCount').textContent=doctors.length; document.getElementById('tableTitle').textContent='Planning — '+m.label; renderKpis(m,doctors); renderTable(m,doctors);}
function countCode(doctors,codes){let n=0; doctors.forEach(d=>d.cells.forEach(v=>{const x=norm(v); if(codes.includes(x)||codes.includes(x.toLowerCase())) n++;})); return n;}
function renderKpis(m,doctors){const el=document.getElementById('kpis'); el.innerHTML=''; const vals=[['Médecins',doctors.length],['Gardes 24h',countCode(doctors,['G'])],['Journées 18h',countCode(doctors,['18','18h'])],['Repos garde',countCode(doctors,['RG'])],['Absences A',countCode(doctors,['A'])]]; vals.forEach(([label,val])=>{const div=document.createElement('div'); div.className='kpi'; div.innerHTML=`<small>${label}</small><strong>${val}</strong>`; el.appendChild(div);});}
function renderTable(m,doctors){const table=document.getElementById('planningTable'); let html='<thead><tr><th class="doctor">Médecin</th>'; m.days.forEach(d=>{html+=`<th class="day ${isWeekend(d.weekday)?'weekend-head':''}"><div>${d.day}</div><small>${d.weekday}</small></th>`}); html+='</tr></thead><tbody>'; doctors.forEach(doc=>{html+=`<tr><th class="doctor">${doc.name}</th>`; m.days.forEach((d,i)=>{const val=norm(doc.cells[i]); const wk=isWeekend(d.weekday)?' weekend':''; html+=`<td class="cell${wk}">${val?`<span class="chip ${codeClass(val)}" title="${codeLabels[val]||val}">${val}</span>`:'<span class="empty">·</span>'}</td>`}); html+='</tr>';}); html+='</tbody>'; table.innerHTML=html;}
init().catch(err=>{document.body.innerHTML='<pre>Erreur de chargement : '+err.message+'</pre>';});
